const SUPABASE_URL=window.PASION_SUPABASE_URL||"";
const SUPABASE_ANON_KEY=window.PASION_SUPABASE_ANON_KEY||"";
const $=s=>document.querySelector(s);
const loginView=$("#loginView"),dashboardView=$("#dashboardView"),loginForm=$("#loginForm"),loginMessage=$("#loginMessage"),adminMessage=$("#adminMessage"),userEmail=$("#userEmail"),logoutBtn=$("#logoutBtn"),refreshBtn=$("#refreshBtn"),moduleNav=$("#moduleNav"),dashboardModule=$("#dashboardModule"),dataModule=$("#dataModule"),settingsModule=$("#settingsModule"),moduleTitle=$("#moduleTitle"),moduleDescription=$("#moduleDescription"),moduleEyebrow=$("#moduleEyebrow"),tableTitle=$("#tableTitle"),tableEyebrow=$("#tableEyebrow"),tableHead=$("#tableHead"),tableBody=$("#tableBody"),moduleFilters=$("#moduleFilters"),recordCount=$("#recordCount"),createBtn=$("#createBtn"),recordModal=$("#recordModal"),modalTitle=$("#modalTitle"),modalEyebrow=$("#modalEyebrow"),modalClose=$("#modalClose"),modalCancel=$("#modalCancel"),recordForm=$("#recordForm"),recordFields=$("#recordFields"),formMessage=$("#formMessage"),quoteItems=$("#quoteItems");
const STATUSES=["new","contacted","qualified","quoted","won","lost","archived"];
const ROLES=["admin","manager","operator"];
let client=null,currentUser=null,currentProfile=null,currentModule="dashboard",editingId=null,moduleRows=[],relationCache={};

const MODULES={
 leads:{title:"Leads",desc:"Consultas comerciales captadas desde el sitio y WhatsApp.",table:"leads",search:["name","email","whatsapp","destination","trip_type"],fields:[
 ["name","Nombre","text",true],["email","Email","email"],["whatsapp","WhatsApp","text"],["language","Idioma","select",false,["es","pt","en"]],["trip_type","Tipo de viaje","text"],["destination","Destino","text"],["travel_start","Inicio","date"],["travel_end","Fin","date"],["travelers","Viajeros","number"],["message","Mensaje","textarea"],["source","Origen","text",false,["website","whatsapp","manual"]],["status","Estado","select",false,STATUSES],["assigned_to","Responsable","relation:profiles"]]},
 clients:{title:"Clientes",desc:"Personas que pasaron de consulta a relación comercial.",table:"clients",search:["name","email","whatsapp"],fields:[["name","Nombre","text",true],["email","Email","email"],["whatsapp","WhatsApp","text"],["language","Idioma","select",false,["es","pt","en"]],["lead_id","Lead relacionado","relation:leads"],["notes","Notas","textarea"]]},
 suppliers:{title:"Proveedores",desc:"Red de ejecución, costos, condiciones y alternativas.",table:"suppliers",search:["name","service_type","city","summa_status"],fields:[
 ["name","Proveedor","text",true],["service_type","Servicio","text",true],["contact_name","Contacto","text"],["email","Email","email"],["whatsapp","WhatsApp","text"],["city","Ciudad","text"],["zone","Zona","text"],["languages","Idiomas","array"],["capacity","Capacidad","number"],["net_price","Costo neto","number"],["currency","Moneda","select",false,["ARS","USD","BRL","EUR"]],["availability","Disponibilidad","text"],["lead_time_hours","Lead time (h)","number"],["payment_method","Método de pago","text"],["cancellation_policy","Cancelación","textarea"],["inclusions","Incluye","textarea"],["exclusions","No incluye","textarea"],["documentation","Documentación","textarea"],["emergency_contact","Contacto emergencia","text"],["alternative_supplier_id","Proveedor alternativo","relation:suppliers"],["summa_status","Estado Summa","select",false,["candidate","validate","excluded"]],["status","Estado operativo","select",false,["active","inactive"]],["notes","Notas","textarea"]]},
 experiences:{title:"Experiencias",desc:"Catálogo vendible vinculado a proveedor y ejecución verificada.",table:"experiences",search:["name","category","destination"],fields:[
 ["name","Experiencia","text",true],["slug","Slug","text"],["category","Categoría","text",true],["description","Descripción","textarea"],["destination","Destino","text",true],["supplier_id","Proveedor","relation:suppliers",true],["cost","Costo","number",true],["currency","Moneda","select",true,["ARS","USD","BRL","EUR"]],["margin","Margen %","number",true],["sale_price","Precio venta","number",true],["active","Activa","boolean"],["execution_verified","Ejecución verificada","boolean"]]},
 quotes:{title:"Cotizaciones",desc:"Presupuestos comerciales con items, costos, precios y validez.",table:"quotes",search:["status","currency"],fields:[
 ["client_id","Cliente","relation:clients",true],["lead_id","Lead","relation:leads"],["status","Estado","select",false,["draft","sent","accepted","rejected","expired"]],["currency","Moneda","select",true,["ARS","USD","BRL","EUR"]],["subtotal","Subtotal","number"],["discount","Descuento","number"],["total","Total","number"],["valid_until","Válida hasta","date"],["notes","Notas","textarea"]]},
 reservations:{title:"Reservas",desc:"Servicios confirmados y vínculo con proveedor y cliente.",table:"reservations",search:["status","confirmation_code"],fields:[
 ["quote_id","Cotización","relation:quotes"],["client_id","Cliente","relation:clients",true],["supplier_id","Proveedor","relation:suppliers"],["status","Estado","select",false,["pending","confirmed","cancelled","completed"]],["service_date","Fecha servicio","date"],["confirmation_code","Código confirmación","text"],["supplier_cost","Costo proveedor","number"],["sale_amount","Importe venta","number"],["currency","Moneda","select",false,["ARS","USD","BRL","EUR"]],["notes","Notas","textarea"]]},
 payments:{title:"Pagos",desc:"Cobros de clientes y pagos a proveedores.",table:"payments",search:["direction","status","reference"],fields:[
 ["client_id","Cliente","relation:clients"],["reservation_id","Reserva","relation:reservations"],["direction","Dirección","select",true,["incoming","outgoing"]],["status","Estado","select",false,["pending","paid","failed","refunded","cancelled"]],["amount","Importe","number",true],["currency","Moneda","select",true,["ARS","USD","BRL","EUR"]],["method","Método","text"],["reference","Referencia","text"],["paid_at","Fecha de pago","datetime-local"],["notes","Notas","textarea"]]},
 operations:{title:"Operaciones",desc:"Centro de ejecución: responsables, horarios, pickups e incidencias.",table:"operations",search:["status","pickup_location","dropoff_location"],fields:[
 ["reservation_id","Reserva","relation:reservations",true],["status","Estado","select",false,["pending","confirmed","in_progress","completed","incident","cancelled"]],["assigned_to","Responsable","relation:profiles"],["scheduled_at","Fecha/hora","datetime-local"],["pickup_location","Pickup","text"],["dropoff_location","Dropoff","text"],["instructions","Instrucciones","textarea"],["incident_notes","Incidencias","textarea"]]},
 audit:{title:"Auditoría",desc:"Registro de acciones administrativas. Solo lectura.",table:"audit_logs",search:["entity_type","action","entity_id"],readOnly:true,fields:[
 ["created_at","Fecha","datetime-local"],["actor_id","Actor","relation:profiles"],["entity_type","Entidad","text"],["entity_id","ID","text"],["action","Acción","text"],["details","Detalle","json"]]},
 profiles:{title:"Usuarios",desc:"Perfiles internos y roles administrativos. La cuenta Auth se gestiona en Supabase.",table:"profiles",search:["full_name","role"],profile:true,fields:[["full_name","Nombre","text"],["role","Rol","select",true,ROLES]]}
};
const PERMS={
 admin:{create:["leads","clients","suppliers","experiences","quotes","reservations","payments","operations","profiles"],edit:["leads","clients","suppliers","experiences","quotes","reservations","payments","operations","profiles"],delete:["clients","suppliers","experiences","quotes","reservations","payments","operations"]},
 manager:{create:["clients","suppliers","experiences","quotes","reservations","payments","operations"],edit:["leads","clients","suppliers","experiences","quotes","reservations","payments","operations"],delete:["clients","suppliers","experiences","quotes","reservations","payments","operations"]},
 operator:{create:["clients","operations"],edit:["leads","clients","operations"],delete:[]}
};
function can(action,table){return !!(PERMS[currentProfile?.role||"operator"]?.[action]||[]).includes(table)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmt(v,key){if(v===null||v===undefined||v==="")return "-";if(key==="details"&&typeof v==="object")return esc(JSON.stringify(v));if(key.includes("_at")||key==="service_date"||key==="valid_until"){const d=new Date(v);return isNaN(d)?esc(v):new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:key==="created_at"||key==="updated_at"||key==="paid_at"||key==="scheduled_at"?"short":undefined}).format(d)}if(typeof v==="object")return esc(JSON.stringify(v));if(key==="execution_verified"||key==="active")return v?"Sí":"No";return esc(v)}
function labelFor(table,row){if(!row)return"-";if(table==="profiles")return row.full_name||row.id;return row.name||row.full_name||row.email||row.confirmation_code||row.id}
async function relationOptions(kind){if(relationCache[kind])return relationCache[kind];const table=kind==="profiles"?"profiles":kind;const {data}=await client.from(table).select("*").limit(200).order(table==="profiles"?"full_name":"name",{ascending:true});relationCache[kind]=data||[];return relationCache[kind]}
async function audit(action,entity,entityId,details){if(!currentUser||!client)return;const {error}=await client.from("audit_logs").insert({actor_id:currentUser.id,entity_type:entity,entity_id:entityId||null,action,details:details||{}});if(error)console.warn("audit log:",error.message)}
function msg(v){if(adminMessage)adminMessage.textContent=v||""}
function setLoginMessage(v){loginMessage.textContent=v||""}
function showLogin(){loginView.classList.remove("hidden");dashboardView.classList.add("hidden");setLoginMessage("")}
function showApp(){loginView.classList.add("hidden");dashboardView.classList.remove("hidden");userEmail.textContent=currentUser?.email||""}
function renderDashboard(counts){leadCount.textContent=counts.leads.total;newLeadCount.textContent=counts.leads.new;qualifiedLeadCount.textContent=counts.leads.qualified;wonLeadCount.textContent=counts.leads.won;reservationCount.textContent=counts.reservations;paymentCount.textContent=counts.payments;operationCount.textContent=counts.operations;experienceCount.textContent=counts.experiences;statusSummary.innerHTML=STATUSES.map(s=>`<div><span>${s}</span><strong>${counts.leads[s]||0}</strong></div>`).join("")}
async function loadDashboard(){if(!client||!currentUser)return;const counts={leads:{total:0},reservations:0,payments:0,operations:0,experiences:0};STATUSES.forEach(s=>counts.leads[s]=0);const queries=await Promise.all(["leads","reservations","payments","operations","experiences"].map(t=>client.from(t).select("*",{count:"exact",head:false}).limit(1000)));queries.forEach((r,i)=>{if(r.error)return;const table=["leads","reservations","payments","operations","experiences"][i];if(table==="leads"){counts.leads.total=r.data?.length||0;(r.data||[]).forEach(x=>{if(counts.leads[x.status]!==undefined)counts.leads[x.status]++})}else counts[table]=r.data?.length||0});renderDashboard(counts)}
function showDashboard(){currentModule="dashboard";moduleNav.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.module==="dashboard"));moduleTitle.textContent="Dashboard";moduleDescription.textContent="Vista general del negocio receptivo.";moduleEyebrow.textContent="CENTRO DE OPERACIONES";dashboardModule.classList.remove("hidden");dataModule.classList.add("hidden");settingsModule.classList.add("hidden");loadDashboard()}
function showSettings(){currentModule="settings";dashboardModule.classList.add("hidden");dataModule.classList.add("hidden");settingsModule.classList.remove("hidden");moduleTitle.textContent="Configuración";moduleDescription.textContent="Preferencias y reglas operativas del backoffice.";moduleEyebrow.textContent="CONFIGURACIÓN"}
async function loadModule(name){const cfg=MODULES[name];if(!cfg)return;currentModule=name;dashboardModule.classList.add("hidden");settingsModule.classList.add("hidden");dataModule.classList.remove("hidden");moduleEyebrow.textContent="BACKOFFICE";moduleTitle.textContent=cfg.title;moduleDescription.textContent=cfg.desc;tableEyebrow.textContent=cfg.table.toUpperCase();tableTitle.textContent=cfg.title;msg("");createBtn.classList.toggle("hidden",!!cfg.readOnly||!can("create",cfg.table));moduleFilters.innerHTML='<input id="quickFilter" placeholder="Buscar en este módulo…"><select id="statusFilter"><option value="">Todos los registros</option></select>';tableHead.innerHTML="<tr>"+cfg.fields.map(f=>"<th>"+esc(f[1])+"</th>").join("")+"<th>Acciones</th></tr>";tableBody.innerHTML='<tr><td colspan="'+(cfg.fields.length+1)+'">Cargando…</td></tr>';if(!client||!currentUser){tableBody.innerHTML='<tr><td colspan="'+(cfg.fields.length+1)+'">Sesión requerida.</td></tr>';return}
const {data,error}=await client.from(cfg.table).select("*").order("created_at",{ascending:false});if(error){tableBody.innerHTML='<tr><td colspan="'+(cfg.fields.length+1)+'">No se pudieron cargar los registros. Revisá permisos y RLS.</td></tr>';msg(error.message);return}moduleRows=data||[];recordCount.textContent=moduleRows.length;
const values=[...new Set(moduleRows.map(r=>r.status).filter(Boolean))];$("#statusFilter").innerHTML='<option value="">Todos los registros</option>'+values.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join("");
const render=()=>{const q=($("#quickFilter")?.value||"").toLowerCase(),sf=$("#statusFilter")?.value||"";const rows=moduleRows.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!sf||r.status===sf));tableBody.innerHTML=rows.length?rows.map(row=>"<tr>"+cfg.fields.map(f=>"<td>"+(f[2]?.startsWith("relation:")?esc(labelFor(f[2].slice(9),relationCache[f[2].slice(9)]?.find(x=>x.id===row[f[0]]))):fmt(row[f[0]],f[0]))+"</td>").join("")+"<td>"+(cfg.readOnly?"":((can("edit",cfg.table)?'<button class="table-action edit-btn" data-id="'+row.id+'">Editar</button> ':'')+(can("delete",cfg.table)?'<button class="table-action delete-btn" data-id="'+row.id+'">Eliminar</button>':'')))+"</td></tr>").join(""):'<tr><td colspan="'+(cfg.fields.length+1)+'">No hay registros.</td></tr>'};
await Promise.all([...new Set(cfg.fields.filter(f=>f[2]?.startsWith("relation:")).map(f=>f[2].slice(9)))].map(relationOptions));render();$("#quickFilter").addEventListener("input",render);$("#statusFilter").addEventListener("change",render)}
function inputFor(f,value){const [key,label,type,required,opts]=f;const val=value===undefined||value===null?"":value;let html="";if(type==="boolean")return '<label class="check-field"><input name="'+key+'" type="checkbox" '+(val?"checked":"")+'> '+esc(label)+'</label>';if(type==="select")html='<select name="'+key+'" '+(required?"required":"")+'><option value="">Seleccionar…</option>'+opts.map(o=>'<option value="'+esc(o)+'" '+(String(o)===String(val)?"selected":"")+'>'+esc(o)+'</option>').join("")+"</select>";else if(type?.startsWith("relation:")){const kind=type.slice(9),items=relationCache[kind]||[];html='<select name="'+key+'" '+(required?"required":"")+'><option value="">Seleccionar…</option>'+items.map(o=>'<option value="'+o.id+'" '+(String(o.id)===String(val)?"selected":"")+'>'+esc(labelFor(kind,o))+'</option>').join("")+"</select>"}else if(type==="textarea")html='<textarea name="'+key+'" '+(required?"required":"")+'>'+esc(val)+'</textarea>';else if(type==="json")html='<textarea name="'+key+'">'+esc(typeof val==="object"?JSON.stringify(val):val)+'</textarea>';else html='<input name="'+key+'" type="'+(type||"text")+'" value="'+esc(val)+'" '+(required?"required":"")+">";return '<label>'+esc(label)+html+'</label>'}
async function openModal(name,id){const cfg=MODULES[name];if(!cfg||cfg.readOnly)return;editingId=id||null;modalEyebrow.textContent=cfg.table.toUpperCase();modalTitle.textContent=(id?"Editar ":"Nuevo ")+cfg.title;formMessage.textContent="";const row=id?moduleRows.find(x=>x.id===id)||{}:{};const relations=[...new Set(cfg.fields.filter(f=>f[2]?.startsWith("relation:")).map(f=>f[2].slice(9)))];await Promise.all(relations.map(relationOptions));recordFields.innerHTML=cfg.fields.map(f=>'<div class="'+(f[2]==="textarea"||f[2]==="json"?"full":"")+'">'+inputFor(f,row[f[0]])+"</div>").join("");quoteItems.classList.toggle("hidden",name!=="quotes");if(name==="quotes")await renderQuoteItems(row);recordModal.classList.remove("hidden")}
async function renderQuoteItems(row){let items=[];if(editingId){const r=await client.from("quote_items").select("*").eq("quote_id",editingId);items=r.data||[]}quoteItems.dataset.items=JSON.stringify(items);quoteItems.innerHTML='<h3>Items de la cotización</h3><div id="quoteItemRows"></div><button type="button" id="addQuoteItem" class="ghost">+ Agregar experiencia</button>';const rows=$("#quoteItemRows");const render=()=>{const data=JSON.parse(quoteItems.dataset.items||"[]");rows.innerHTML=data.map((it,i)=>'<div class="quote-item"><select data-k="experience_id" data-i="'+i+'"><option value="">Experiencia</option>'+((relationCache.experiences||[]).map(x=>'<option value="'+x.id+'" '+(x.id===it.experience_id?"selected":"")+'>'+esc(x.name)+'</option>').join(""))+'</select><select data-k="supplier_id" data-i="'+i+'"><option value="">Proveedor</option>'+((relationCache.suppliers||[]).map(x=>'<option value="'+x.id+'" '+(x.id===it.supplier_id?"selected":"")+'>'+esc(x.name)+'</option>').join(""))+'</select><input data-k="description" data-i="'+i+'" value="'+esc(it.description||"")+'" placeholder="Descripción"><input data-k="quantity" data-i="'+i+'" type="number" min="1" value="'+(it.quantity||1)+'" placeholder="Cant."><input data-k="unit_cost" data-i="'+i+'" type="number" min="0" step="0.01" value="'+(it.unit_cost||0)+'" placeholder="Costo"><input data-k="unit_price" data-i="'+i+'" type="number" min="0" step="0.01" value="'+(it.unit_price||0)+'" placeholder="Precio"><button type="button" class="ghost remove-item" data-i="'+i+'">×</button></div>').join("")};await Promise.all([relationOptions("experiences"),relationOptions("suppliers")]);render();rows.addEventListener("input",e=>{const i=Number(e.target.dataset.i),k=e.target.dataset.k;if(!k)return;const d=JSON.parse(quoteItems.dataset.items||"[]");d[i][k]=e.target.value;quoteItems.dataset.items=JSON.stringify(d)});rows.addEventListener("click",e=>{if(!e.target.classList.contains("remove-item"))return;const d=JSON.parse(quoteItems.dataset.items||"[]");d.splice(Number(e.target.dataset.i),1);quoteItems.dataset.items=JSON.stringify(d);render()});$("#addQuoteItem").addEventListener("click",()=>{const d=JSON.parse(quoteItems.dataset.items||"[]");d.push({quantity:1,unit_cost:0,unit_price:0});quoteItems.dataset.items=JSON.stringify(d);render()})}
function closeModal(){recordModal.classList.add("hidden");editingId=null}
async function saveRecord(e){e.preventDefault();const cfg=MODULES[currentModule];if(!cfg||!client)return;formMessage.textContent="Guardando…";const fd=new FormData(recordForm),payload={};cfg.fields.forEach(f=>{const key=f[0],type=f[2];if(type==="boolean")payload[key]=fd.get(key)==="on";else{let v=fd.get(key);if(v==="")v=null;if(type==="number"&&v!==null)v=Number(v);if(type==="array"&&v!==null)v=v.split(",").map(x=>x.trim()).filter(Boolean);if(type==="json"&&v!==null){try{v=JSON.parse(v)}catch{throw new Error("El JSON no es válido en "+key)}}payload[key]=v}});if(currentModule==="experiences"){if(!payload.supplier_id||payload.cost===null||payload.cost===undefined)throw new Error("Una experiencia necesita proveedor y costo.");if(payload.active&&!payload.execution_verified)throw new Error("No se puede activar una experiencia sin ejecución verificada.");if(payload.supplier_id){const s=(relationCache.suppliers||[]).find(x=>x.id===payload.supplier_id);if(s?.summa_status==="excluded")throw new Error("No se puede usar un proveedor excluido por el filtro Summa.")}}
if(currentModule==="reservations"&&payload.status==="confirmed"&&!payload.supplier_id)throw new Error("Una reserva confirmada necesita proveedor.");
if(currentModule==="operations"&&!payload.reservation_id)throw new Error("La operación necesita una reserva.");
if(currentModule==="quotes"){const subtotal=Number(payload.subtotal||0),discount=Number(payload.discount||0);payload.total=Math.max(0,subtotal-discount)}
let result;if(editingId)result=await client.from(cfg.table).update(payload).eq("id",editingId).select().single();else{if(currentModule==="quotes"&&currentUser)payload.created_by=currentUser.id;result=await client.from(cfg.table).insert(payload).select().single()}if(result.error){formMessage.textContent=result.error.message;return}
const entityId=result.data?.id||editingId;await audit(editingId?"update":"create",cfg.table,entityId,{changes:payload});
if(currentModule==="quotes"){const items=JSON.parse(quoteItems.dataset.items||"[]");if(editingId)await client.from("quote_items").delete().eq("quote_id",editingId);if(items.length){const clean=items.filter(i=>i.description||i.experience_id).map(i=>({...i,quote_id:entityId,quantity:Number(i.quantity||1),unit_cost:Number(i.unit_cost||0),unit_price:Number(i.unit_price||0)}));if(clean.length){const ir=await client.from("quote_items").insert(clean);if(ir.error){formMessage.textContent="Cotización guardada, pero fallaron los items: "+ir.error.message;return}}}}
closeModal();relationCache={};await loadModule(currentModule)}
async function deleteRecord(id){const cfg=MODULES[currentModule];if(!can("delete",cfg.table))return;if(!confirm("¿Eliminar este registro? Esta acción no se puede deshacer desde el panel."))return;const {error}=await client.from(cfg.table).delete().eq("id",id);if(error){msg(error.message);return}await audit("delete",cfg.table,id);relationCache={};await loadModule(currentModule)}
moduleNav.addEventListener("click",e=>{const btn=e.target.closest(".nav-item");if(!btn)return;moduleNav.querySelectorAll(".nav-item").forEach(b=>b.classList.remove("active"));btn.classList.add("active");if(btn.dataset.module==="dashboard")showDashboard();else if(btn.dataset.module==="settings")showSettings();else loadModule(btn.dataset.module)});
tableBody.addEventListener("click",e=>{const edit=e.target.closest(".edit-btn"),del=e.target.closest(".delete-btn");if(edit)openModal(currentModule,edit.dataset.id);if(del)deleteRecord(del.dataset.id)});
createBtn.addEventListener("click",()=>openModal(currentModule));refreshBtn.addEventListener("click",()=>currentModule==="dashboard"?showDashboard():currentModule==="settings"?showSettings():loadModule(currentModule));modalClose.addEventListener("click",closeModal);modalCancel.addEventListener("click",closeModal);recordForm.addEventListener("submit",async e=>{try{await saveRecord(e)}catch(err){formMessage.textContent=err.message||"No se pudo guardar."}});recordModal.addEventListener("click",e=>{if(e.target===recordModal)closeModal()});
loginForm.addEventListener("submit",async e=>{e.preventDefault();if(!client){setLoginMessage("Supabase no está configurado.");return}setLoginMessage("Ingresando…");const {error}=await client.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error)setLoginMessage(error.message);});
logoutBtn.addEventListener("click",async()=>{if(client)await client.auth.signOut();showLogin()});
async function boot(){if(!window.supabase||!SUPABASE_URL||!SUPABASE_ANON_KEY){setLoginMessage("Supabase no está configurado.");return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data}=await client.auth.getSession();if(data.session){await establishSession(data.session)}else showLogin();client.auth.onAuthStateChange((_event,session)=>{if(session)establishSession(session);else showLogin()})}
async function establishSession(session){currentUser=session.user;const {data,error}=await client.from("profiles").select("*").eq("id",currentUser.id).single();if(error||!data){setLoginMessage("La cuenta existe, pero no tiene un perfil staff válido.");await client.auth.signOut();return}currentProfile=data;showApp();showDashboard()}
boot();